const formatDate = () => {
  let date = new Date();
  let formattedDate =
    date.getFullYear() +
    "-" +
    (date.getMonth() + 1).toString().padStart(2, "0") +
    "-" +
    date.getDate().toString().padStart(2, "0");

  return formattedDate;
};

export const defaultPreferences = {
  homeWarranty: null,
  filterByFurnished: null,
  specific_keywords_or_phrases: null,
  propertyAmenities: {
    securityCameras: false,
    pool: false,
    laundry: false,
    garden: false,
    dishWasher: false,
    internet: false,
    garage: false,
    elevator: false,
    jacuzzi: false,
  },
  architecturalStyles: {
    colonial: false,
    contemporary: false,
    craftsman: false,
    others: false,
  },
  virtualTours: null,
  propertyType: null,
  closeProximities: {
    nearbySchools: false,
    nearbyAirports: false,
    nearbyGardens: false,
    nearbyHospitals: false,
    nearbyUniversity: false,
    nearbyCollege: false,
  },
  homeTypes: {
    singleFamily: false,
    multiFamily: false,
    others: false,
  },
  min_priceRange: 0,
  max_priceRange: 0,
  min_constructionDateRange: null,
  max_constructionDateRange: null,
  min_sizeConsiderationsRange: 0,
  max_sizeConsiderationsRange: 0,
  propertyCategory: null,
  location: {
    city: null,
    neighborhood: null,
    zipCode: null,
    landmarks: null,
  },
};
export const questionsForNormaluser = [
  {
    key: "homeWarranty",
    text: "Do you want a home warranty?",
    options: [
      "All Warranties",
      "Home Warranty Available",
      "Home Warranty Unavailable",
    ],
    type: "radio",
  },
  {
    key: "filterByFurnished",
    text: "Do you want to filter by furnished properties?",
    options: ["Furnished Properties", "Unfurnished Properties"],
    type: "radio",
  },
  {
    key: "specific_keywords_or_phrases",
    text: "Enter specific keywords or phrases:",
    options: [""],
    type: "input",
  },
  {
    key: "propertyAmenities",
    text: "Select property amenities you want:",
    options: [
      "Security Cameras",
      "Pool",
      "Laundry",
      "Garden",
      "Dish Washer",
      "Internet",
      "Garage",
      "Elevator",
      "Jacuzzi",
    ],
    type: "checkbox",
  },
  {
    key: "architecturalStyles",
    text: "Select architectural styles you want:",
    options: ["Colonial", "Contemporary", "Craftsman", "Others"],
    type: "checkbox",
  },
  {
    key: "virtualTours",
    text: "Do you want virtual tours?",
    options: ["Virtual Tours Only", "All Listings"],
    type: "radio",
  },
  {
    key: "propertyType",
    text: "Enter property type you want:",
    options: ["For Sale", "For Rent", "New Construction", "Recently Sold"],
    type: "radio",
  },
  {
    key: "closeProximities",
    text: "Select close proximities:",
    options: [
      "Nearby Schools",
      "Nearby Airports",
      "Nearby Gardens",
      "Nearby Hospitals",
      "Nearby University",
      "Nearby College",
    ],
    type: "checkbox",
  },
  {
    key: "homeTypes",
    text: "Select home types you want:",
    options: ["Single-Family", "Multi-Family", "Others"],
    type: "checkbox",
  },
  {
    key: "priceRange",
    text: "Enter price range:",
    options: [""],
    type: "range",
    label: "price",
  },
  {
    key: "constructionDateRange",
    text: "Enter construction date range:",
    options: [""],
    type: "date",
  },
  {
    key: "sizeConsiderationsRange",
    text: "Enter size considerations range:",
    options: [""],
    type: "range",
    label: "size",
  },
  {
    key: "propertyCategory",
    text: "Enter property category:",
    options: ["House", "Apartment", "Condo", "Townhouse", "Land", "Commercial"],
    type: "radio",
  },
  {
    key: "location",
    text: "Enter location details:",
    options: ["city", "neighborhood", "zipCode", "landmarks", "Skip"],
    type: "location",
  },
];

export const realtorQuestions = [];

export const defaultPreferencesForProfessionals = {
  propertySpecialization: {
    residential: false,
    commercial: false,
    luxury: false,
    mixedUse: false,
  },
  preferredPropertyTypes: {
    singleFamilyHomes: false,
    condos: false,
    officeSpaces: false,
    retailSpaces: false,
    industrialProperties: false,
  },
  min_priceRange: 0,
  max_priceRange: 0,
  geographicAreas: {
    cityCenter: false,
    suburbs: false,
    ruralAreas: false,
    specificNeighborhoods: false,
  },
  excellingRegions: null,

  min_idealClientDemographicsAge: 0,
  max_idealClientDemographicsAge: 0,
  min_idealClientDemographicsIncome: 0,
  max_idealClientDemographicsIncome: 0,
  idealClientDemographicsFamilyStatus: {
    single: false,
    married: false,
    divorced: false,
    inARelationship: false,
  },
  idealClientDemographicsOccupation: {
    healthcare: false,
    education: false,
    engineering: false,
    informationTechnology: false,
    finance: false,
    law: false,
    salesAndMarketing: false,
    construction: false,
    manufacturing: false,
    artsAndEntertainment: false,
    scienceAndResearch: false,
    publicServiceAndGovernment: false,
    transportationAndLogistics: false,
    hospitalityAndTourism: false,
    agriculture: false,
  },
  clientSpecialization: {
    firstTimeHomebuyers: false,
    retirees: false,
    investors: false,
    relocatingClients: false,
  },
  commonClientNeeds: {
    investmentProperties: false,
    relocation: false,
    downsizing: false,
    upgrading: false,
  },
  specificClientPreferences: {
    ecoFriendlyHomes: false,
    historicProperties: false,
    accessibleProperties: false,
    smartHomes: false,
  },
  communicationPreferences: {
    phoneCalls: false,
    emails: false,
    textMessages: false,
    inPersonMeetings: false,
    videoCalls: false,
  },
  communicationTools: {
    crmSoftware: false,
    emailMarketingPlatforms: false,
    virtualMeetingTools: false,
  },
  additionalServices: {
    staging: false,
    propertyManagement: false,
    investmentAnalysis: false,
    marketResearch: false,
  },
  valueAddedServices: {
    homeRenovationConsultation: false,
    legalAssistance: false,
    financialPlanningServices: false,
  },
  marketingStrategies: {
    onlineAdvertising: false,
    socialMediaMarketing: false,
    openHouses: false,
    printAdvertising: false,
  },
  successfulMarketingChannels: {
    facebookAds: false,
    instagramMarketing: false,
    localEventsSponsorship: false,
  },
  clientRelationshipManagement: {
    regularFollowUps: false,
    clientAppreciationEvents: false,
    referralPrograms: false,
  },
  postTransactionFollowUp: {
    quarterlyNewsletters: false,
    annualCheckIns: false,
    specialOccasionGreetings: false,
  },
  professionalExperience: null,
  specializedCertifications: null,
  goalsExpectations: {
    leadConversionRate: false,
    clientSatisfaction: false,
    transactionVolume: false,
  },
  measuringSuccess: {
    positiveReviewsTestimonials: false,
    repeatBusiness: false,
    referralRate: false,
  },
  // Add more properties based on the categories provided...
};

export const questionsForProfessionals = [
  {
    key: "propertySpecialization",
    text: "What type of properties do you specialize in?",
    options: ["Residential", "Commercial", "Luxury", "Mixed-Use"],
    type: "checkbox",
  },
  {
    key: "preferredPropertyTypes",
    text: "What are the preferred property types?",
    options: [
      "Single-Family Homes",
      "Condos",
      "Office Spaces",
      "Retail Spaces",
      "Industrial Properties",
    ],
    type: "checkbox",
  },
  {
    key: "priceRange",
    text: "What price range do your clients typically look for?",
    options: [""], // Placeholder for range input
    type: "range",
    label: "price",
  },
  {
    key: "geographicAreas",
    text: "What geographic areas do you primarily serve?",
    options: [
      "City Center",
      "Suburbs",
      "Rural Areas",
      "Specific Neighborhoods",
    ],
    type: "checkbox",
  },
  {
    key: "excellingRegions",
    text: "Are there specific neighborhoods or regions where you excel?",
    options: [""], // Placeholder for input
    type: "input",
  },

  {
    key: "idealClientDemographicsAge",
    text: "What is the age brackets of your ideal clients?",

    options: [""],
    type: "range",
    label: "",
  },
  {
    key: "idealClientDemographicsIncome",
    text: "What is the income level of your ideal clients?",

    options: [""],
    type: "range",
    label: "",
  },
  {
    key: "idealClientDemographicsOccupation",
    text: "What are the occupations of your ideal clients?",

    options: [
      "Healthcare",
      "Education",
      "Engineering",
      "Information Technology",
      "Finance",
      "Law",
      "Sales and Marketing",
      "Construction",
      "Manufacturing",
      "Arts and Entertainment",
      "Science and Research",
      "Public Service and Government",
      "Transportation and Logistics",
      "Hospitality and Tourism",
      "Agriculture",
    ],
    type: "checkbox",
  },
  {
    key: "idealClientDemographicsFamilyStatus",
    text: "What is the family status of your ideal clients?",

    options: ["Single", "Married", "Divorced", "In a Relationship"],
    type: "checkbox",
  },
  {
    key: "clientSpecialization",
    text: "Do you specialize in working with certain buyer or seller demographics?",
    options: [
      "First-Time Homebuyers",
      "Retirees",
      "Investors",
      "Relocating Clients",
    ],
    type: "checkbox",
  },
  {
    key: "commonClientNeeds",
    text: "What are the common needs and goals of your clients?",
    options: ["Investment Properties", "Relocation", "Downsizing", "Upgrading"],
    type: "checkbox",
  },
  {
    key: "specificClientPreferences",
    text: "Do you have experience working with clients with specific needs or preferences?",
    options: [
      "Eco-friendly Homes",
      "Historic Properties",
      "Accessible Properties",
      "Smart Homes",
    ],
    type: "checkbox",
  },
  {
    key: "communicationPreferences",
    text: "How do you prefer to communicate with your clients?",
    options: [
      "Phone Calls",
      "Emails",
      "Text Messages",
      "In-Person Meetings",
      "Video Calls",
    ],
    type: "checkbox",
  },
  {
    key: "communicationTools",
    text: "Are there any specific communication tools or platforms you use?",
    options: [
      "CRM Software",
      "Email Marketing Platforms",
      "Virtual Meeting Tools",
    ],
    type: "checkbox",
  },
  {
    key: "additionalServices",
    text: "What services do you provide to your clients beyond traditional transactions?",
    options: [
      "Staging",
      "Property Management",
      "Investment Analysis",
      "Market Research",
    ],
    type: "checkbox",
  },
  {
    key: "valueAddedServices",
    text: "Are there any additional resources or value-added services you offer?",
    options: [
      "Home Renovation Consultation",
      "Legal Assistance",
      "Financial Planning Services",
    ],
    type: "checkbox",
  },
  {
    key: "marketingStrategies",
    text: "What marketing strategies do you employ to attract and engage clients?",
    options: [
      "Online Advertising",
      "Social Media Marketing",
      "Open Houses",
      "Print Advertising",
    ],
    type: "checkbox",
  },
  {
    key: "successfulMarketingChannels",
    text: "Are there any specific marketing channels or tactics that have been particularly successful for you?",
    options: [
      "Facebook Ads",
      "Instagram Marketing",
      "Local Events Sponsorship",
    ],
    type: "checkbox",
  },
  {
    key: "clientRelationshipManagement",
    text: "How do you nurture and maintain relationships with past clients and referrals?",
    options: [
      "Regular Follow-ups",
      "Client Appreciation Events",
      "Referral Programs",
    ],
    type: "checkbox",
  },
  {
    key: "postTransactionFollowUp",
    text: "Do you have a system in place for staying in touch with clients after transactions are completed?",
    options: [
      "Quarterly Newsletters",
      "Annual Check-ins",
      "Special Occasion Greetings",
    ],
    type: "checkbox",
  },
  {
    key: "professionalExperience",
    text: "What is your background and experience in the real estate industry?",
    options: [
      // "Years of Experience",
      // "Previous Transactions",
      // "Areas of Expertise",
    ],
    type: "user_input",
  },
  {
    key: "specializedCertifications",
    text: "Do you have any specialized certifications, designations, or areas of expertise?",
    options: [
      // "REALTOR® Designation",
      // "Certified Residential Specialist (CRS)",
      // "Accredited Buyer's Representative (ABR)",
    ],
    type: "user_input",
  },
  {
    key: "goalsExpectations",
    text: "What are your goals and expectations for working with leads generated through the system?",
    options: [
      "Lead Conversion Rate",
      "Client Satisfaction",
      "Transaction Volume",
    ],
    type: "checkbox",
  },
  {
    key: "measuringSuccess",
    text: "How do you measure success in your client relationships and transactions?",
    options: [
      "Positive Reviews/Testimonials",
      "Repeat Business",
      "Referral Rate",
    ],
    type: "checkbox",
  },
  // Add more questions based on the categories provided...
];

export const filters = [
  {
    key: "location",
    text: "Location",
    desc: "Enter City, neighborhood, ZIP code, or specific location",
    options: ["city", "neighborhood", "zipCode", "landmarks", "Skip"],
    type: "location",
  },

  {
    key: "propertyType",
    text: "Property Type",
    options: ["Residential", "Luxury", "Commercial", "Mixed-Use",  "Condo", "Apartment"],
    type: "radio",
  },
  {
    key: "priceRange",
    text: "Price range",
    options: [""],
    type: "range",
    label: "price",
    min: 0,
    max: 5000000,
  },
  {
    key: "noOfBedrooms",
    text: "No. of Bedrooms",
    options: [""],
    type: "range",
    label: "",
    min: 0,
    max: 50,
  },
  {
    key: "noOfBathrooms",
    text: "No. of Bathrooms",
    options: [""],
    type: "range",
    label: "",
    min: 0,
    max: 50,
  },
  {
    key: "squareFootage",
    text: "Square Footage",
    options: [""],
    type: "range",
    label: "",
    min: 0,
    max: 5000000,
  },
  {
    key: "lotSize",
    text: "Lot Size",
    options: [""],
    type: "range",
    label: "",
    min: 0,
    max: 5000000,
  },
  {
    key: "yearBuilt",
    text: "Year Built",
    options: [""],
    type: "date",
    label: "",
  },
  {
    key: "homeTypes",
    text: "Home Type",
    options: ["All", "Single Family", "Multi Family", "Others"],
    type: "checkbox",
  },
  {
    key: "propertyAmenities",
    text: "Amenities",
    options: [
      "Security Cameras",
      "Pool",
      "Laundry",
      "Garden",
      "Dish Washer",
      "Internet",
      "Garage",
      "Elevator",
      "Jacuzzi",
    ],
    type: "checkbox",
  },
  {
    key: "closeProximities",
    text: "Close Proximities",
    options: [
      "Nearby Schools",
      "Nearby Airports",
      "Nearby Gardens",
      "Nearby Hospitals",
      "Nearby University",
      "Nearby College",
    ],
    type: "checkbox",
  },
  {
    key: "walkability",
    text: "Walkability",
    desc: "Walk Score or proximity to public transportation",
    options: [],
    type: "number_input",
    min: 0,
    max: 50000,
  },

  {
    key: "HOAFees",
    text: "HOA Fees",
    desc: " Presence and amount of Homeowners Association fees",
    options: ["Yes", "No"],
    type: "radio",
  },
  {
    key: "petFriendly",
    text: "Pet-Friendly",
    desc: "",
    options: ["Yes", "No"],
    type: "radio",
  },
  {
    key: "accessibilityFeatures",
    text: "Accessibility Features",
    options: ["Laundry", "WheelChair Accessibility", "Dish Washer", "Elevator"],
    type: "checkbox",
  },
  {
    key: "viewType",
    text: "View Type",
    options: ["City View", "Mountain View", "Water Front"],
    type: "checkbox",
  },
  {
    key: "parking",
    text: "Parking",
    desc: "",
    options: ["Yes", "No"],
    type: "radio",
  },
  {
    key: "listingType",
    text: "Listing Type",
    options: ["For Sale", "For Rent", "New Construction", "Recently Sold"],
    type: "checkbox",
  },
  {
    key: "shortSale",
    text: "Short Sale",
    desc: "Option to filter distressed properties",
    options: ["All", "Yes", "No"],
    type: "radio",
  },
  {
    key: "interiorFeatures",
    text: "Interior Features",
    options: ["Hardword Floors", "Granite Countertops"],
    type: "checkbox",
  },
  {
    key: "energyEfficiency",
    text: "Energy Efficiency",
    desc: "Filter for energy-efficient properties",
    options: ["All", "Yes", "No"],
    type: "radio",
  },
  {
    key: "virtualTours",
    text: "Virtual Tour Availability",
    desc: "Properties with virtual tours or 3D walkthroughs",
    options: ["All", "Yes", "No"],
    type: "radio",
  },
  {
    key: "homeStyle",
    text: "Home Style",
    desc: "Architectural styles",
    options: ["All", "Colonial", "Contemporary", "Craftsman"],
    type: "checkbox",
  },
  {
    key: "Acreage",
    text: "acreage",
    desc: "For properties with specific acreage requirements",
    options: [""],
    type: "range",
    min: 0,
    max: 150,
    label: "",
  },
  {
    key: "specific_keywords_or_phrases",
    text: "Custom Keywords",
    desc: "Input specific keywords or phrases",
    options: [""],
    type: "keyword_input",
  },
  {
    key: "Furnished",
    text: "Furnished",
    desc: "Filter based on furnished or unfurnished properties",
    options: ["All", "Yes", "No"],
    type: "radio",
  },
  {
    key: "homeWarranty",
    text: "Home Warranty",
    desc: "Filter for properties with a home warranty",
    options: ["All", "Yes", "No"],
    type: "radio",
  },
  {
    key: "securityFeatures",
    text: "Security Features",
    desc: "Architectural styles",
    options: ["Security Systems", "Gated Communities"],
    type: "checkbox",
  },
];
